// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QAgentApi.Data;

#nullable disable

namespace QAgentApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260109192919_09.01.2026v2")]
    partial class _09012026v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QAgentApi.Model.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecutionReportId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ExecutionReportId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionReport", b =>
                {
                    b.Property<int>("ExecutionReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExecutionReportId"));

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExecutionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecutionRunId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int");

                    b.HasKey("ExecutionReportId");

                    b.HasIndex("ExecutionRunId")
                        .IsUnique();

                    b.HasIndex("TestCaseId");

                    b.ToTable("ExecutionReports");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionRun", b =>
                {
                    b.Property<int>("ExecutionRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExecutionRunId"));

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ExecutionRunId");

                    b.ToTable("ExecutionRuns");
                });

            modelBuilder.Entity("QAgentApi.Model.Organisation", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrgId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("QAgentApi.Model.TestCase", b =>
                {
                    b.Property<int>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestCaseId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrganisationOrgId")
                        .HasColumnType("int");

                    b.Property<int?>("TestSuiteId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TestCaseId");

                    b.HasIndex("OrganisationOrgId");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("UserId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("QAgentApi.Model.TestStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int");

                    b.HasKey("StepId");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestSteps");
                });

            modelBuilder.Entity("QAgentApi.Model.TestSuite", b =>
                {
                    b.Property<int>("TestSuiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestSuiteId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestSuiteId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("TestSuites");
                });

            modelBuilder.Entity("QAgentApi.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QAgentApi.Model.Comment", b =>
                {
                    b.HasOne("QAgentApi.Model.ExecutionReport", "ExecutionReport")
                        .WithMany("Comments")
                        .HasForeignKey("ExecutionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionReport");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionReport", b =>
                {
                    b.HasOne("QAgentApi.Model.ExecutionRun", "ExecutionRun")
                        .WithOne("ExecutionReport")
                        .HasForeignKey("QAgentApi.Model.ExecutionReport", "ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAgentApi.Model.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("QAgentApi.Model.TestCase", b =>
                {
                    b.HasOne("QAgentApi.Model.Organisation", null)
                        .WithMany("TestCases")
                        .HasForeignKey("OrganisationOrgId");

                    b.HasOne("QAgentApi.Model.TestSuite", null)
                        .WithMany("TestCases")
                        .HasForeignKey("TestSuiteId");

                    b.HasOne("QAgentApi.Model.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("QAgentApi.Model.TestStep", b =>
                {
                    b.HasOne("QAgentApi.Model.TestCase", "TestCase")
                        .WithMany("TestSteps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("QAgentApi.Model.TestSuite", b =>
                {
                    b.HasOne("QAgentApi.Model.Organisation", "Organisation")
                        .WithMany("TestSuites")
                        .HasForeignKey("OrganisationId");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("QAgentApi.Model.User", b =>
                {
                    b.HasOne("QAgentApi.Model.Organisation", "Organisation")
                        .WithMany("Employees")
                        .HasForeignKey("OrganisationId");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionReport", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionRun", b =>
                {
                    b.Navigation("ExecutionReport");
                });

            modelBuilder.Entity("QAgentApi.Model.Organisation", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("TestCases");

                    b.Navigation("TestSuites");
                });

            modelBuilder.Entity("QAgentApi.Model.TestCase", b =>
                {
                    b.Navigation("TestSteps");
                });

            modelBuilder.Entity("QAgentApi.Model.TestSuite", b =>
                {
                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
