// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QAgentApi.Data;

#nullable disable

namespace QAgentApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260206171116_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QAgentApi.Model.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExecutionReportId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ExecutionReportId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionReport", b =>
                {
                    b.Property<int>("ExecutionReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExecutionReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExecutionDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExecutionRunId")
                        .HasColumnType("int");

                    b.Property<bool>("Failed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Passed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RecordingAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RecordingBase64")
                        .HasColumnType("longtext");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaskDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ExecutionReportId");

                    b.HasIndex("ExecutionRunId")
                        .IsUnique();

                    b.HasIndex("TestCaseId");

                    b.ToTable("ExecutionReports");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionRun", b =>
                {
                    b.Property<int>("ExecutionRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExecutionRunId"));

                    b.Property<string>("CheckStatusUrl")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "check_status_at");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<bool>("RecordingEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "recording_enabled");

                    b.Property<string>("ReportUrl")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "report_at");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "success");

                    b.Property<string>("TaskId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "task_id");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int");

                    b.HasKey("ExecutionRunId");

                    b.HasIndex("TestCaseId");

                    b.ToTable("ExecutionRuns");
                });

            modelBuilder.Entity("QAgentApi.Model.Organisation", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrgId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("OrgId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("QAgentApi.Model.TestCase", b =>
                {
                    b.Property<int>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TestCaseId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OrganisationOrgId")
                        .HasColumnType("int");

                    b.Property<int?>("TestSuiteId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TestCaseId");

                    b.HasIndex("OrganisationOrgId");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("UserId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("QAgentApi.Model.TestStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StepId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int");

                    b.HasKey("StepId");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestSteps");
                });

            modelBuilder.Entity("QAgentApi.Model.TestSuite", b =>
                {
                    b.Property<int>("TestSuiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TestSuiteId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TestSuiteId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("TestSuites");
                });

            modelBuilder.Entity("QAgentApi.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QAgentApi.Model.Comment", b =>
                {
                    b.HasOne("QAgentApi.Model.ExecutionReport", "ExecutionReport")
                        .WithMany("Comments")
                        .HasForeignKey("ExecutionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionReport");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionReport", b =>
                {
                    b.HasOne("QAgentApi.Model.ExecutionRun", "ExecutionRun")
                        .WithOne("ExecutionReport")
                        .HasForeignKey("QAgentApi.Model.ExecutionReport", "ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAgentApi.Model.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionRun", b =>
                {
                    b.HasOne("QAgentApi.Model.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("QAgentApi.Model.TestCase", b =>
                {
                    b.HasOne("QAgentApi.Model.Organisation", null)
                        .WithMany("TestCases")
                        .HasForeignKey("OrganisationOrgId");

                    b.HasOne("QAgentApi.Model.TestSuite", null)
                        .WithMany("TestCases")
                        .HasForeignKey("TestSuiteId");

                    b.HasOne("QAgentApi.Model.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("QAgentApi.Model.TestStep", b =>
                {
                    b.HasOne("QAgentApi.Model.TestCase", "TestCase")
                        .WithMany("TestSteps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("QAgentApi.Model.TestSuite", b =>
                {
                    b.HasOne("QAgentApi.Model.Organisation", "Organisation")
                        .WithMany("TestSuites")
                        .HasForeignKey("OrganisationId");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("QAgentApi.Model.User", b =>
                {
                    b.HasOne("QAgentApi.Model.Organisation", "Organisation")
                        .WithMany("Employees")
                        .HasForeignKey("OrganisationId");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionReport", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("QAgentApi.Model.ExecutionRun", b =>
                {
                    b.Navigation("ExecutionReport");
                });

            modelBuilder.Entity("QAgentApi.Model.Organisation", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("TestCases");

                    b.Navigation("TestSuites");
                });

            modelBuilder.Entity("QAgentApi.Model.TestCase", b =>
                {
                    b.Navigation("TestSteps");
                });

            modelBuilder.Entity("QAgentApi.Model.TestSuite", b =>
                {
                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
